# Generated by Django 4.1 on 2023-07-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movieapp", "0002_remove_movies_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="img",
            field=models.ImageField(default="kurama", upload_to="gallery"),
            preserve_default=False,
        ),
    ]
